version: "3"
services:

  gotrue:
    image: supabase/gotrue:latest
    ports:
      - "9999:9999"
    env_file:
      - .env
    depends_on:
      -  postgres
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres.dev
    container_name: gotrue_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      # sets the schema name, this should match the `NAMESPACE` env var set in your .env file
      - DB_NAMESPACE=auth