/*
 * Gotrue API
 *
 * Gotrue Go API client
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type AdminUser struct {
	Aud string `json:"aud"`

	Role string `json:"role"`

	Email string `json:"Email"`

	Phone string `json:"Phone"`

	Password *string `json:"Password,omitempty"`

	EmailConfirm bool `json:"EmailConfirm"`

	PhoneConfirm bool `json:"PhoneConfirm"`

	BanDuration string `json:"BanDuration"`
}
