name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags: ['*']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: supabase/postgres:14.1.0
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
      gotrue:
        image: supabase/gotrue:latest
        env:
          GOTRUE_MAILER_URLPATHS_CONFIRMATION: '/verify'
          GOTRUE_JWT_SECRET: '37c304f8-51aa-419a-a1af-06154e63707a'
          GOTRUE_JWT_EXP: 3600
          GOTRUE_DB_DRIVER: postgres
          DB_NAMESPACE: auth
          GOTRUE_API_HOST: 0.0.0.0
          PORT: 9999
          GOTRUE_DISABLE_SIGNUP: 'false'
          API_EXTERNAL_URL: http://localhost:9999
          GOTRUE_SITE_URL: http://localhost:9999
          GOTRUE_URI_ALLOW_LIST: https://supabase.io/docs
          GOTRUE_MAILER_AUTOCONFIRM: 'false'
          GOTRUE_LOG_LEVEL: DEBUG
          GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
          DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
          GOTRUE_EXTERNAL_GOOGLE_ENABLED: 'true'
          GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: 53566906701-bmhc1ndue7hild39575gkpimhs06b7ds.apps.googleusercontent.com
          GOTRUE_EXTERNAL_GOOGLE_SECRET: Sm3s8RE85rDcS36iMy8YjrpC
          GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: http://localhost:9999/callback
          GOTRUE_SMTP_HOST: mail
          GOTRUE_SMTP_PORT: 2500
          GOTRUE_SMTP_USER: GOTRUE_SMTP_USER
          GOTRUE_SMTP_PASS: GOTRUE_SMTP_PASS
          GOTRUE_SMTP_ADMIN_EMAIL: admin@email.com
          GOTRUE_MAILER_SUBJECTS_CONFIRMATION: 'Please confirm'
          GOTRUE_EXTERNAL_PHONE_ENABLED: 'true'
          GOTRUE_SMS_PROVIDER: "twilio"
          GOTRUE_SMS_TWILIO_ACCOUNT_SID: "${GOTRUE_SMS_TWILIO_ACCOUNT_SID}"
          GOTRUE_SMS_TWILIO_AUTH_TOKEN: "${GOTRUE_SMS_TWILIO_AUTH_TOKEN}"
          GOTRUE_SMS_TWILIO_MESSAGE_SERVICE_SID: "${GOTRUE_SMS_TWILIO_MESSAGE_SERVICE_SID}"
          GOTRUE_SMS_AUTOCONFIRM: 'false'
          GOTRUE_COOKIE_KEY: "sb"
        ports:
          - 9999:9999
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          skip-unshallow: "true"
      - name: Test
        run: make test